//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSelfHost.ProxyClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/WCFSelfHost.Host")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FarbeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HerstellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Farbe {
            get {
                return this.FarbeField;
            }
            set {
                if ((object.ReferenceEquals(this.FarbeField, value) != true)) {
                    this.FarbeField = value;
                    this.RaisePropertyChanged("Farbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hersteller {
            get {
                return this.HerstellerField;
            }
            set {
                if ((object.ReferenceEquals(this.HerstellerField, value) != true)) {
                    this.HerstellerField = value;
                    this.RaisePropertyChanged("Hersteller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modell {
            get {
                return this.ModellField;
            }
            set {
                if ((object.ReferenceEquals(this.ModellField, value) != true)) {
                    this.ModellField = value;
                    this.RaisePropertyChanged("Modell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PS {
            get {
                return this.PSField;
            }
            set {
                if ((this.PSField.Equals(value) != true)) {
                    this.PSField = value;
                    this.RaisePropertyChanged("PS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAutoService")]
    public interface IAutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAutos", ReplyAction="http://tempuri.org/IAutoService/GetAutosResponse")]
        WCFSelfHost.ProxyClient.ServiceReference1.Auto[] GetAutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/GetAutos", ReplyAction="http://tempuri.org/IAutoService/GetAutosResponse")]
        System.Threading.Tasks.Task<WCFSelfHost.ProxyClient.ServiceReference1.Auto[]> GetAutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddAuto", ReplyAction="http://tempuri.org/IAutoService/AddAutoResponse")]
        void AddAuto(WCFSelfHost.ProxyClient.ServiceReference1.Auto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoService/AddAuto", ReplyAction="http://tempuri.org/IAutoService/AddAutoResponse")]
        System.Threading.Tasks.Task AddAutoAsync(WCFSelfHost.ProxyClient.ServiceReference1.Auto auto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutoServiceChannel : WCFSelfHost.ProxyClient.ServiceReference1.IAutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoServiceClient : System.ServiceModel.ClientBase<WCFSelfHost.ProxyClient.ServiceReference1.IAutoService>, WCFSelfHost.ProxyClient.ServiceReference1.IAutoService {
        
        public AutoServiceClient() {
        }
        
        public AutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFSelfHost.ProxyClient.ServiceReference1.Auto[] GetAutos() {
            return base.Channel.GetAutos();
        }
        
        public System.Threading.Tasks.Task<WCFSelfHost.ProxyClient.ServiceReference1.Auto[]> GetAutosAsync() {
            return base.Channel.GetAutosAsync();
        }
        
        public void AddAuto(WCFSelfHost.ProxyClient.ServiceReference1.Auto auto) {
            base.Channel.AddAuto(auto);
        }
        
        public System.Threading.Tasks.Task AddAutoAsync(WCFSelfHost.ProxyClient.ServiceReference1.Auto auto) {
            return base.Channel.AddAutoAsync(auto);
        }
    }
}
